version: "3"

services:
  server:
    container_name: server
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - ${APP_PORT:-3000}:${APP_PORT:-3000}
    env_file:
      - backend/.env
    depends_on:
      database:
        condition: service_healthy
    command: sh -c "npm run prisma:dev && npm run start:dev"
    volumes:
      - ./backend:/app 
  
  database:
    container_name: database
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: $DOCKER_POSTGRES_PASSWORD
    ports:
      - ${DOCKER_LOCAL_POSTGRES_PORT:-5432}:5432
    env_file:
      - .env
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
